name: Generate Documentation

on:
  create:
    ref_type: tag

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install the dependencies
        run: yarn --ignore-scripts

      - name: Generate the documentation
        run: yarn docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
